// ── Feature Roadmap Data ─────────────────────────────────────────────────
// MANUAL layer — edit this file to update feature roadmap status.
// Auto-generated gameData.js handles ticket counts; this handles feature stages.
//
// TRACK STATUS OPTIONS:
//   "not-started" | "in-progress" | "review" | "done" | "blocked" | "live"
//
// TRACKS: design → art → techArt → dev → qa → release
// ─────────────────────────────────────────────────────────────────────────

export const FEATURE_ROADMAP = {
  wm: [
    {
      id: "wm-m7",
      name: "Collectible Event",
      subtitle: "Gems / Lanterns / Chain Tiles",
      version: "1.46.0",
      milestone: "M7",
      targetMonth: "Apr 2026",
      status: "live",
      weekStart: 0,   // week index from Apr 21 (0 = Apr W3)
      tracks: {
        design:  { status: "done",        note: "Spec finalised — Didara",         weekStart: 0, weekEnd: 1 },
        art:     { status: "done",        note: "Assets delivered — Juan Z",       weekStart: 0, weekEnd: 1 },
        techArt: { status: "done",        note: "Integration done — Juan Z",       weekStart: 1, weekEnd: 2 },
        dev:     { status: "done",        note: "Live @ 10% Android — Toni",       weekStart: 1, weekEnd: 2 },
        qa:      { status: "done",        note: "Signed off — Krish",             weekStart: 2, weekEnd: 2 },
      },
      jiraEpic: null,
      risks: [],
      kpiTarget: "D1–D3 retention uplift",
    },
    {
      id: "wm-m8",
      name: "Beginner's Bonus",
      subtitle: "Jigsaw Puzzle + feature foreshadowing",
      version: "1.47.0",
      milestone: "M8",
      targetMonth: "Apr 2026",
      status: "in-progress",
      weekStart: 0,
      tracks: {
        design:  { status: "done",        note: "Spec complete — Didara",          weekStart: 0, weekEnd: 1 },
        art:     { status: "done",        note: "Assets delivered — Juan Z",       weekStart: 0, weekEnd: 1 },
        techArt: { status: "done",        note: "Prefabs created — Juan S",        weekStart: 1, weekEnd: 2 },
        dev:     { status: "review",      note: "11 tickets Ready for QA",         weekStart: 1, weekEnd: 2 },
        qa:      { status: "not-started", note: "Waiting — tickets unassigned ⚠️", weekStart: 2, weekEnd: 3 },
      },
      jiraEpic: null,
      risks: ["11 QA tickets unassigned — Krish not yet briefed"],
      kpiTarget: "D2–D3 retention uplift",
    },
    {
      id: "wm-m9",
      name: "Word Master Chained Reward",
      subtitle: "",
      version: "1.48.0",
      milestone: "M9",
      targetMonth: "May 2026",
      status: "planned",
      weekStart: 2,
      tracks: {
        design:  { status: "in-progress", note: "Spec in progress — Didara",       weekStart: 2, weekEnd: 3 },
        art:     { status: "not-started", note: "",                                 weekStart: 3, weekEnd: 4 },
        techArt: { status: "not-started", note: "",                                 weekStart: 4, weekEnd: 5 },
        dev:     { status: "not-started", note: "",                                 weekStart: 4, weekEnd: 6 },
        qa:      { status: "not-started", note: "",                                 weekStart: 6, weekEnd: 7 },
      },
      jiraEpic: null,
      risks: [],
      kpiTarget: "D1–D3 retention uplift",
    },
    {
      id: "wm-m10",
      name: "Breather Levels",
      subtitle: "New gameplay mode",
      version: "1.49.0",
      milestone: "M10",
      targetMonth: "Jun 2026",
      status: "planned",
      weekStart: 5,
      tracks: {
        design:  { status: "not-started", note: "",  weekStart: 5, weekEnd: 6 },
        art:     { status: "not-started", note: "",  weekStart: 6, weekEnd: 7 },
        techArt: { status: "not-started", note: "",  weekStart: 7, weekEnd: 8 },
        dev:     { status: "not-started", note: "",  weekStart: 7, weekEnd: 9 },
        qa:      { status: "not-started", note: "",  weekStart: 9, weekEnd: 9 },
      },
      jiraEpic: null,
      risks: [],
      kpiTarget: "D3–D7 retention uplift",
    },
    {
      id: "wm-m11",
      name: "Meta Progress + FTUE Polish",
      subtitle: "",
      version: "1.50.0",
      milestone: "M11",
      targetMonth: "Jun 2026",
      status: "planned",
      weekStart: 7,
      tracks: {
        design:  { status: "not-started", note: "",  weekStart: 7, weekEnd: 8 },
        art:     { status: "not-started", note: "",  weekStart: 8, weekEnd: 9 },
        techArt: { status: "not-started", note: "",  weekStart: 8, weekEnd: 9 },
        dev:     { status: "not-started", note: "",  weekStart: 8, weekEnd: 9 },
        qa:      { status: "not-started", note: "",  weekStart: 9, weekEnd: 9 },
      },
      jiraEpic: null,
      risks: [],
      kpiTarget: "D1→D3–D7 uplift",
    },
  ],

  sol: [
    {
      id: "sol-coins-meta",
      name: "Coins Meta System",
      subtitle: "Coins behind cards + booster purchase",
      version: "v5.7.x",
      milestone: "",
      targetMonth: "Apr 2026",
      status: "in-progress",
      weekStart: 0,
      tracks: {
        design:  { status: "done",        note: "Spec complete — Srikanth",         weekStart: 0, weekEnd: 1 },
        art:     { status: "done",        note: "UI assets complete — Henrique",    weekStart: 0, weekEnd: 1 },
        techArt: { status: "done",        note: "Integration — Juan Z",             weekStart: 1, weekEnd: 2 },
        dev:     { status: "review",      note: "Angel — multiple tickets in QA",   weekStart: 1, weekEnd: 2 },
        qa:      { status: "in-progress", note: "Krish — active testing",           weekStart: 2, weekEnd: 3 },
      },
      jiraEpic: null,
      risks: ["v4.3.4 still has 139K users — multi-version QA burden ongoing"],
      kpiTarget: "Engagement + monetisation",
    },
    {
      id: "sol-level-up",
      name: "Level Up Screen",
      subtitle: "New level up animation + results screen",
      version: "v5.7.x",
      milestone: "",
      targetMonth: "Apr 2026",
      status: "in-progress",
      weekStart: 0,
      tracks: {
        design:  { status: "done",        note: "Spec complete — Srikanth",         weekStart: 0, weekEnd: 1 },
        art:     { status: "in-progress", note: "Henrique — In Progress",           weekStart: 0, weekEnd: 2 },
        techArt: { status: "not-started", note: "Waiting on art",                   weekStart: 2, weekEnd: 3 },
        dev:     { status: "not-started", note: "Blocked on art completion",        weekStart: 2, weekEnd: 3 },
        qa:      { status: "not-started", note: "",                                  weekStart: 3, weekEnd: 4 },
      },
      jiraEpic: "CHSOL-1367",
      risks: [],
      kpiTarget: "D1 retention",
    },
    {
      id: "sol-journey-liveops",
      name: "Journey / Live Ops",
      subtitle: "Journey system using live ops infrastructure",
      version: "v5.8.0",
      milestone: "",
      targetMonth: "May 2026",
      status: "in-progress",
      weekStart: 1,
      tracks: {
        design:  { status: "done",        note: "Spec complete — Giulia",           weekStart: 0, weekEnd: 1 },
        art:     { status: "not-started", note: "",                                  weekStart: 3, weekEnd: 4 },
        techArt: { status: "not-started", note: "",                                  weekStart: 4, weekEnd: 5 },
        dev:     { status: "in-progress", note: "Angel — CHSOL-1357 In Progress",   weekStart: 1, weekEnd: 4 },
        qa:      { status: "not-started", note: "",                                  weekStart: 5, weekEnd: 6 },
      },
      jiraEpic: "CHSOL-1357",
      risks: ["Depends on MetaPlay live ops infrastructure — scope TBD"],
      kpiTarget: "D7+ retention",
    },
    {
      id: "sol-quest-popup",
      name: "Quest Popup Phase 2",
      subtitle: "New quest popup design + flow",
      version: "v5.8.0",
      milestone: "",
      targetMonth: "May 2026",
      status: "in-progress",
      weekStart: 1,
      tracks: {
        design:  { status: "done",        note: "Design complete",                  weekStart: 0, weekEnd: 1 },
        art:     { status: "not-started", note: "",                                  weekStart: 2, weekEnd: 3 },
        techArt: { status: "not-started", note: "",                                  weekStart: 3, weekEnd: 4 },
        dev:     { status: "in-progress", note: "Murat — CHSOL-1358 Backlog",       weekStart: 1, weekEnd: 3 },
        qa:      { status: "not-started", note: "",                                  weekStart: 4, weekEnd: 5 },
      },
      jiraEpic: "CHSOL-1358",
      risks: [],
      kpiTarget: "D3–D7 retention",
    },
  ],
};

// Track display metadata
export const TRACK_LABELS = {
  design:  "Design",
  art:     "Art",
  techArt: "Tech Art",
  dev:     "Dev",
  qa:      "QA",
};

// Status display config
export const TRACK_STATUS_CONFIG = {
  "not-started": { label: "Not started", bar: "#D8DCE5", text: "#8B93A8", bg: "transparent"  },
  "in-progress":  { label: "In progress", bar: "#4A7BB5", text: "#4A7BB5", bg: "#EEF4FB"     },
  "review":       { label: "Review",      bar: "#F4A428", text: "#B07020", bg: "#FEF5E8"     },
  "done":         { label: "Done",        bar: "#3E9E6A", text: "#2E8A5A", bg: "#E8F5EE"     },
  "blocked":      { label: "Blocked",     bar: "#C05040", text: "#8A3828", bg: "#FCEAE6"     },
  "live":         { label: "Live",        bar: "#3E9E6A", text: "#2E8A5A", bg: "#E8F5EE"     },
};
